##### Test creating Tensor

In [2]:
import sys
sys.path.append('./python')
import needle as ndl
import numpy as np
from needle.init import randb,one_hot

array = ndl.rand(2,3,4)

tensor = randb(2,3,4)
i = ndl.Tensor([[1,2,3],[2,3,4]])

one_hot = one_hot(10, i)
print(tensor)

using numpy backend
rand shape: (2, 3, 4)
[[[1. 0. 0. 0.]
  [0. 1. 0. 1.]
  [0. 0. 1. 1.]]

 [[0. 0. 0. 1.]
  [0. 1. 0. 0.]
  [0. 0. 0. 0.]]]


##### Test Op and autograd

test add

In [2]:
import sys
sys.path.append('./python')
import needle as ndl
import numpy as np
tensor1 = ndl.ones(3, requires_grad = True)
tensor2 = ndl.Tensor([2,3,4])
res = tensor1 + tensor2
print(res.shape)
scalar = 10.0

using numpy backend
(3,)


test sub mul power and div

In [3]:
res = tensor1 - scalar
print(res)
res2 = tensor1 * scalar
print(res2)
res3 = tensor2 ** scalar
print(res3)
res4 = tensor1 / scalar
print(res4)

[-9. -9. -9.]
[10. 10. 10.]
[1.024000e+03 5.904900e+04 1.048576e+06]
[0.1 0.1 0.1]


test **sum broadcast_to transpose and reshape**

In [12]:
# tensor = ndl.rand(2,3,4,requires_grad=True)
# sum_ = tensor.sum(axes=(0,1))
# print(sum_)
# sum_.backward()
# print(tensor.grad)

rand shape: (2, 3, 4)
[2.1483262 2.8686392 3.3586063 4.083393 ]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


test **matmul**

In [4]:
tensor3 = ndl.rand(3,4)
tensor4 = ndl.rand(4,5)
res = tensor3 @ tensor4
print(res.shape)

rand shape: (3, 4)
rand shape: (4, 5)
(3, 5)


#### question 以及面试官可能问到的question？


#### 写代码过程中遇到的困难以及如何解决的？


In [8]:
import torch

tensor1 = torch.rand(2,3,4)
tensor2 = torch.rand(2,3,4)
tensor3 = torch.stack((tensor1, tensor2))
print(tensor3.shape)

torch.Size([2, 2, 3, 4])


6
